
# 站点配置
baseURL = "https://acm.rogery.dev"
languageCode = "zh"
title = "Roger Young"
theme = "hugo-pure"

# 可以删除用不到的配置，不建议移动顺序

# 底部版权信息，支持 md
Copyright = "© 2021 [Roger Young](https://acm.rogery.dev)"



# 导航栏目录
[[params.menu]]
name = "Post"
url = "/post"

[[params.menu]]
name = "Tags"
url = "/tags"

[[params.menu]]
name = "About"
url = "/about"


[markup.tableOfContents]
# <ol> 目录
ordered = true
[markup.highlight]
# 不内置 chroma 的 css
noClasses = true
# 关闭 chroma 高亮
codeFences = false
[markup.goldmark.render]
# 允许 md 插入 html 标签
unsafe = true
[markup.goldmark.extensions]
# 魔改的 hugo, 见 https://github.com/rogeryoungh/hugo-patch
LaTeX = true


# 标题栏
[params.header]
avatar = "https://rogery.dev/img/logo.png"
name = "rogeryoungh"
link = "https://rogery.dev/"


# KaTeX 公式渲染
[params.katex]
enable = false


# Prism 代码高亮
[params.prism]
enable = false


# valine 评论
[params.valine]
enable = false
appId = ""
appKey = ""
avatar = "mp"
placeholder = "说点什么吧..."
visitor = false


# giscus 评论
[params.giscus]
enable = false
repo = ""
repoId = ""
category = ""
categoryId = ""
mapping = ""
strict = ""
reactionsEnabled = ""
emitMetadata = ""
inputPosition = ""
lang = ""


# 目录
[params.toc]
enable = true


[outputs]
home = ["HTML", "RSS", "JSON"]
